tetris : Main.o Grille.o Menu.o Piece.o Verif.o Score.o
	gcc -o tetris Main.o Grille.o Menu.o Piece.o Verif.o Score.o

Main.o : Main.c
	gcc -o Main.o -c Main.c

Grille.o : Grille.c
	gcc -o Grille.o -c Grille.c

Piece.o : Piece.c
	gcc -o Piece.o -c Piece.c

Menu.o : Menu.c
	gcc -o Menu.o -c Menu.c

Verif.o : Verif.c
	gcc -o Verif.o -c Verif.c

Score.o : Score.c
	gcc -o Score.o -c Score.c